import { Ticket } from "../(types)/ticket";

// Mock 티켓 데이터 (10개: 사용 가능 4개, 사용 완료 3개, 기간 만료 3개)
export const MOCK_TICKETS: Ticket[] = [
  // 사용 가능 4개
  {
    id: "1",
    eventName: "21% 파티 입장권",
    eventDate: "2025.12.12",
    eventTime: "14:00",
    location: "서울 성북구",
    qrCode: "TICKET-001-QR",
    status: "upcoming",
    thumbnailUrl: "/images/event-thumbnail.png",
  },
  {
    id: "2",
    eventName: "다시입다연구소 후원자 연말 파티 입장권",
    eventDate: "2025.10.06",
    eventTime: "18:00",
    location: "서울 성북구",
    qrCode: "TICKET-002-QR",
    status: "upcoming",
    thumbnailUrl: "/images/event-thumbnail.png",
  },
  {
    id: "3",
    eventName: "겨울 의류 나눔 행사",
    eventDate: "2025.12.20",
    eventTime: "10:00",
    location: "경기도 수원시",
    qrCode: "TICKET-003-QR",
    status: "upcoming",
    thumbnailUrl: "/images/event-thumbnail.png",
  },
  {
    id: "4",
    eventName: "C 거점공간 교환권",
    eventDate: "2025.09.12",
    eventTime: "13:00",
    location: "C역 스팟",
    qrCode: "TICKET-004-QR",
    status: "upcoming",
    thumbnailUrl: "/images/event-thumbnail.png",
  },
  // 사용 완료 3개
  {
    id: "5",
    eventName: "B 거점공간 교환권",
    eventDate: "2025.11.12",
    eventTime: "11:00",
    location: "B역",
    qrCode: "TICKET-005-QR",
    status: "used",
    thumbnailUrl: "/images/event-thumbnail.png",
  },
  {
    id: "6",
    eventName: "봄맞이 교환회",
    eventDate: "2025.08.15",
    eventTime: "15:30",
    location: "부산 해운대구",
    seat: "B-05",
    qrCode: "TICKET-006-QR",
    status: "used",
    thumbnailUrl: "/images/event-thumbnail.png",
  },
  {
    id: "7",
    eventName: "A 거점공간 교환권",
    eventDate: "2025.07.20",
    eventTime: "14:00",
    location: "A역 스팟",
    qrCode: "TICKET-007-QR",
    status: "used",
    thumbnailUrl: "/images/event-thumbnail.png",
  },
  // 기간 만료 3개
  {
    id: "8",
    eventName: "여름 의류 나눔 행사",
    eventDate: "2025.06.10",
    eventTime: "16:00",
    location: "인천 남동구",
    qrCode: "TICKET-008-QR",
    status: "expired",
    thumbnailUrl: "/images/event-thumbnail.png",
  },
  {
    id: "9",
    eventName: "D 거점공간 교환권",
    eventDate: "2025.05.25",
    eventTime: "12:00",
    location: "D역 스팟",
    qrCode: "TICKET-009-QR",
    status: "expired",
    thumbnailUrl: "/images/event-thumbnail.png",
  },
  {
    id: "10",
    eventName: "봄 의류 교환 페스티벌",
    eventDate: "2025.04.15",
    eventTime: "10:00",
    location: "대구 중구",
    seat: "C-10",
    qrCode: "TICKET-010-QR",
    status: "expired",
    thumbnailUrl: "/images/event-thumbnail.png",
  },
];
